Switch back to dealing with only master.

diff --git a/Tools/chrome-dev/Bin/trunklkgr b/Tools/chrome-dev/Bin/trunklkgr
--- a/Tools/chrome-dev/Bin/trunklkgr
+++ b/Tools/chrome-dev/Bin/trunklkgr
@@ -4,17 +4,17 @@
 progname=`basename $0`
 tf=/tmp/$$.helpfile
 cat > $tf <<EOF
-$progname is a program to bring the core branch (OldGit: trunk, NewGit: master)
+$progname is a program to bring the masetr branch
 of the current git chrome repository to last known good status.
 If a number is provided on the command line, that is the revision to sync to.
 Options:
-	-m		Only valid if done on a branch other than core.
+	-m		Only valid if done on a branch other than master.
 			After executing the base of the command, switch
-			back to this branch and merge core into it.
-	-M		Only valid if done on a branch other than core.
-			If done on a branch other than core, brings
-			core to the "git merge-base' of that branch
-			and the trunk line (i.e. it may move core
+			back to this branch and merge master into it.
+	-M		Only valid if done on a branch other than master.
+			If done on a branch other than master, brings
+			master to the "git merge-base' of that branch
+			and the trunk line (i.e. it may move master
 			forward).
 	-t		Merge to top of tree rather than LKGR.
 	-G		Skip automatic gclient sync.			
@@ -56,22 +56,10 @@ while [ $# -ne 0 ]; do
     shift;
 done
 
-# Am I in the old workflow or the new one?
-workflow=unknown
-case `git config remote.origin.url` in
-    http://git.chromium.org/chromium/src.git)
-        workflow=new;
-	trunkbranch=master;
-	;;
-    http://git.chromium.org/git/chromium.git)
-        workflow=old;
-	trunkbranch=trunk;
-	;;
-esac
-if [ "$workflow" = "unknown" ]; then
-    echo "Unknown remote.origin.url: " `git config remote.origin.url` 1>&2
-    exit 1;
-fi    
+# So that we avoid the funky submodule stuff and can use git svn find-rev.
+originbranch=origin/git-svn
+
+# Assuming new workflow.
 
 # What's my current branch?
 current_branch=`git branch | awk '$1 == "*" {print $2;}'`
@@ -97,14 +85,14 @@ if [ $rev_spec_count -gt 1 ]; then
     exit 1;
 fi  
 
-if [ "$merge_to_original" = "yes" -a "$current_branch" = "$trunkbranch" ]; then
-    echo "Can't merge trunk to original branch if original branch is $trunkbranch!" 1>&2;
+if [ "$merge_to_original" = "yes" -a "$current_branch" = "master" ]; then
+    echo "Can't merge trunk to original branch if original branch is master!" 1>&2;
     exit 1;
 fi
 
 if [ "$merge_to_base" = "yes" ]; then
-    if [ "$current_branch" = "$trunkbranch" ]; then
-        echo "-m only valid on non-$trunkbranch branch." 1>&2;
+    if [ "$current_branch" = "master" ]; then
+        echo "-m only valid on non-master branch." 1>&2;
 	exit 1;
     fi
 
@@ -124,14 +112,14 @@ if [ $# -eq 1 ]; then
     lkgr=$1
 elif [ "$merge_to_base" = "yes" ]; then
     git fetch --all
-    merge_commit="`git merge-base HEAD origin/$trunkbranch`";
+    merge_commit="`git merge-base HEAD $originbranch`";
     lkgr=`git log -1 $merge_commit | sed -n '/git-svn-id/s/^.*@\([0-9]*\) .*$/\1/p'`
     if [ "`echo $lkgr | wc -l`" -ne 1 -o "lkgr" = "" ]; then
         echo "Problem with determining merge base.  Commit: $merge_commit, Revision: $lkgr" 1>&2
 	exit 1;
     fi
 elif [ "$merge_to_tot" = "yes" ]; then
-    lkgr=`git log -1 origin/$trunkbranch | sed -n '/git-svn-id/s/^.*@\([0-9]*\) .*$/\1/p'`
+    lkgr=`git log -1 $originbranch | sed -n '/git-svn-id/s/^.*@\([0-9]*\) .*$/\1/p'`
 else
     lkgr=`curl http://chromium-status.appspot.com/lkgr`
 fi
@@ -139,11 +127,11 @@ echo Syncing to revision $lkgr
 git svn fetch
 lkgr_git_commit=`git svn find-rev r$lkgr`
 
-if [ "$current_branch" = "$trunkbranch" ]; then
+if [ "$current_branch" = "master" ]; then
   # Turns out you can't force update the current branch.  Who knew?
   git reset --hard $lkgr_git_commit
 else
-  git branch -f $trunkbranch $lkgr_git_commit
+  git branch -f master $lkgr_git_commit
 fi
 echo Trunkbranch reset to SVN revision $lkgr
 
@@ -151,9 +139,9 @@ echo Trunkbranch reset to SVN revision $lkgr
 merge_succeeded=0               # If we didn't do it, it suceeded
 if [ "$merge_to_original" = "yes" ]; then
     ## Note that we're still on the starting branch
-    echo "Merging $trunkbranch into $current_branch"
+    echo "Merging master into $current_branch"
     set +e   # Doing my own exit code management for merge.
-    git merge $trunkbranch
+    git merge master
     merge_succeeded=$?
     if [ $merge_succeeded -ne 0 ]; then
         echo "===> Merge Failed."
@@ -161,7 +149,7 @@ if [ "$merge_to_original" = "yes" ]; then
     set -e
 else
     ## If we didn't ask for a merge, we implicitly asked to switch to trunk.
-    git checkout $trunkbranch
+    git checkout master
 fi
 
 if [ "$do_gclient_sync" = "yes" -a $merge_succeeded -eq 0 ]; then
@@ -169,5 +157,5 @@ if [ "$do_gclient_sync" = "yes" -a $merge_succeeded -eq 0 ]; then
 else
     echo "===> Did not do automatic gclient sync."    
 fi
-## Todo: Merge trunkbranch into all branches tracking trunkbranch.  Maybe.
+## Todo: Merge master into all branches tracking master.  Maybe.
 
