Modify error handling.

diff --git a/Tools/chrome-dev/Bin/trunklkgr b/Tools/chrome-dev/Bin/trunklkgr
--- a/Tools/chrome-dev/Bin/trunklkgr
+++ b/Tools/chrome-dev/Bin/trunklkgr
@@ -129,15 +129,18 @@ else
 fi
 echo Trunk branch reset to SVN revision $lkgr
 
+
 merge_succeeded=0               # If we didn't do it, it suceeded
 if [ "$merge_to_original" = "yes" ]; then
     ## Note that we're still on the starting branch
     echo "Merging trunk into $current_branch"
+    set +e   # Doing my own exit code management for merge.
     git merge trunk
     merge_succeeded=$?
     if [ $merge_succeeded -ne 0 ]; then
         echo "===> Merge Failed."
     fi
+    set -e
 else
     ## If we didn't ask for a merge, we implicitly asked to switch to trunk.
     git checkout trunk
